query ItemQuery($path: String!) {
    item(path: $path) {
        id
        name

        fields {
            name
            value
            rendered
        }
       
        children {
            id
            name

            fields {
                name
                value
                rendered
            }
        }
    }
}